### ISSUE TITLE
Uncaught TypeError: Cannot read property 'findTool' of undefined

### ISSUE THREAD

**Issue by danqing** [joefitzgerald/go-get#28]
[Enter steps to reproduce below:]
1. I just saw a blue dialog asking me to download something... Some dependency I'd guess. Then I clicked on it and see the error.

**Atom Version**: 1.10.0-beta6
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [go-get](https://github.com/joefitzgerald/go-get) package, v1.0.4
### Stack Trace

Uncaught TypeError: Cannot read property 'findTool' of undefined

```
At /Users/danqing/.atom/packages/go-get/lib/manager.js:75

TypeError: Cannot read property 'findTool' of undefined
    at Manager.performGet (/Users/danqing/.atom/packages/go-get/lib/manager.js:75:26)
    at HTMLAnchorElement.onDidClick (/Users/danqing/.atom/packages/go-get/lib/manager.js:146:26)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:137:42)
```
### Commands

```
     -0:23.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -0:18.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:17.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:15.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:15.9.0 settings-view:core (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-tree-view",
      "terminal-plus",
      "activate-power-mode"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.4 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-jinja2, v0.5.0 (active)
atom-typescript, v10.1.6 (active)
autocomplete-go, v1.1.1 (inactive)
autocomplete-python, v1.8.6 (active)
blame, v0.10.0 (inactive)
build, v0.65.0 (active)
build-gulp, v0.11.0 (active)
build-make, v0.10.0 (active)
builder-go, v1.0.0 (active)
busy, v0.6.0 (active)
environment, v1.2.0 (active)
file-icons, v1.7.18 (active)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (inactive)
git-control, v0.8.2 (inactive)
go-config, v1.2.2 (inactive)
go-get, v1.0.4 (active)
go-plus, v4.1.0 (active)
gofmt, v1.1.6 (active)
gometalinter-linter, v1.1.0 (active)
gorename, v1.0.2 (active)
jshint, v1.8.6 (active)
language-ini, v1.16.0 (active)
language-jade, v0.7.1 (active)
language-protobuf, v0.7.0 (active)
language-pug, v0.0.17 (active)
language-scala, v1.1.6 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
line-diff-details, v1.3.5 (active)
linter, v1.11.16 (active)
linter-json-lint, v0.1.1 (active)
merge-conflicts, v1.4.4 (active)
navigator-godef, v1.0.3 (active)
pigments, v0.31.2 (active)
react, v0.16.0 (active)
scala-format, v0.1.8 (active)
script, v3.9.0 (inactive)
sort-lines, v0.14.0 (inactive)
symbols-tree-view, v0.13.2 (inactive)
tester-go, v1.0.4 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by joefitzgerald** [comment]
Did you happen to be in the middle of an update when it happened?

**Comment by dcormier** [comment]
I was when it happened to me, @joefitzgerald.

**Comment by Rookcity520** [comment]
Me to, Any fixes?

**Comment by haisum** [comment]
I got the same in middle of an update

**Comment by joefitzgerald** [comment]
I think what is happening is: you're doing updates; you get prompted to install a missing tool; but then the go-get package gets deactivated because it, itself, is being updated. Does that sound right?
