### ISSUE TITLE
Bad argument error after updating

### ISSUE THREAD

**Issue by v3nom** [joefitzgerald/go-get#5]
I was using go-plus for a while and it worked great, but it started to fail after decoupling update.
On startup popup shows that go cover tool is missing even though it was working before and is manually installed. Go get fails with bad argument when I try to install the missing tool. 

I have tried running atom from console and from finder. Same issue. GOPATH is also set and my setup was working before go-plus update.

**Error:**
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:52:14)
    at /Users/togru/.atom/packages/go-config/lib/executor.js:118:29
    at Executor.exec (/Users/togru/.atom/packages/go-config/lib/executor.js:71:12)
    at /Users/togru/.atom/packages/go-get/lib/manager.js:77:30
main.js:91 cover is not available and could not be installed via "go get -u golang.org/x/tools/cmd/cover"; please manually install it to enable display of coverage.

**Comment by joefitzgerald** [comment]
Are you open to a screen sharing session? I cannot reproduce this. Join #go-plus and then direct message me your email address.

[![Slack](https://img.shields.io/badge/atom_slack-%23go--plus-blue.svg?style=flat)](https://atom-slack.herokuapp.com) [![Slack](https://img.shields.io/badge/gophers_slack-%23go--plus-blue.svg?style=flat)](https://gophersinvite.herokuapp.com)
